services:
  canton:
    image: ghcr.io/digital-asset/canton-open-source:latest
    container_name: beet-canton
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    command:
      - daemon
    restart: unless-stopped
